extension KoboldPromptModel {
    public static let defaultSlopList: [String] = [
        "*",
        "...for now.",
        " a reminder",
        " air filled with",
        " air hung thick",
        " air was filled with",
        " air was thick with",
        " an ethereal beauty",
        " brow furrowed in concentration",
        " face whatever challenges",
        " felt a sense of",
        " felt a strange sense",
        " hung heavy in the air",
        " newfound sense of",
        " purred",
        " renewed sense of purpose",
        " something else, something",
        " words hung in the air",
        "'s eye alight",
        "'s eye full",
        "'s eye gleam",
        "'s eye glint",
        "'s eye glow",
        "'s eye shin",
        "'s eye sparkl",
        "'s eye twinkl",
        "'s eyes alight",
        "'s eyes full",
        "'s eyes gleam",
        "'s eyes glint",
        "'s eyes glow",
        "'s eyes shin",
        "'s eyes sparkl",
        "'s eyes twinkl",
        ", eye alight",
        ", eye full",
        ", eye gleam",
        ", eye glint",
        ", eye glow",
        ", eye shin",
        ", eye sparkl",
        ", eye twinkl",
        ", eyes alight",
        ", eyes full",
        ", eyes gleam",
        ", eyes glint",
        ", eyes glow",
        ", eyes shin",
        ", eyes sparkl",
        ", eyes twinkl",
        ", her voice barely",
        ", his voice barely",
        ", if you will,",
        ", my voice barely",
        ", once a ",
        ", their voice barely",
        "a bruising kiss",
        "A dance as old as time",
        "a hint of",
        "A mischievous glint",
        "a mix of confusion and apprehension",
        "a mix of tension and anticipation",
        "a mix of",
        "A moth to a flame",
        "a smile that did not reach",
        "A smirk playing on her lips",
        "a Symphony of",
        "A testament to",
        "a thrill down her spine",
        "Adam's apple bobbing",
        "adam's apple bobbing",
        "admit it",
        "an ethereal beauty",
        "an unspoken tension in",
        "Another day in your life",
        "another day in your life",
        "arched spine",
        "are you ready to navigate the ",
        "arousal pooling in",
        "arousal pooling",
        "as an AI",
        "as you turn to leave",
        "Audible pop",
        "audible pop",
        "ball is in your court",
        "barely a whisper",
        "barely above a whisper",
        "barely above",
        "barely audible",
        "bites her",
        "bites lip",
        "Bites your ear",
        "bites your ear",
        "biting her lip",
        "biting her lower lip",
        "biting my bottom lip",
        "biting my lower lip",
        "blushes bright",
        "Body and soul",
        "body and soul",
        "Bosomy breasts",
        "bosomy breasts",
        "breathless and eager",
        "bruising kiss",
        "bucks",
        "but he can't help it",
        "but she can't help it",
        "but they can't help it",
        "but whatever happens, we",
        "cacophony",
        "Camaraderie",
        "can't help but",
        "Canvas",
        "casting long shadows",
        "catch my drift",
        "cheeks burning",
        "Cheeks flame",
        "cheeks flaming",
        "Cheeks hollowing",
        "cheeks hollowing",
        "cheeks redden",
        "cherub",
        "cherubic",
        "chestnut eyes",
        "chill down her spine",
        "chill run down my spine",
        "chinches her fists",
        "choice is yours",
        "Chuckles darkly",
        "chuckles darkly",
        "clenches around nothing",
        "clenches fists",
        "clenches his fists",
        "clenching fists",
        "clenching her fists",
        "clenching his fists",
        "Cold and calculating",
        "cold and calculating",
        "conspiratorial whisper",
        "conspiratorial whispers",
        "conspiratorial",
        "could not help but",
        "couldn't help but feel",
        "couldn't help but wonder",
        "couldn't help but",
        "couldn't shake the feeling",
        "Couldn’t help but",
        "creamy thigh",
        "crimson",
        "crinkle at the corner",
        "crinkling at the corner",
        "curves in all the right places",
        "dance as old as time",
        "dance of pleasure",
        "dance of",
        "deep shade",
        "deeper shade",
        "despite her",
        "Despite herself",
        "despite herself",
        "despite him",
        "Despite himself",
        "despite himself",
        "despite my",
        "despite them",
        "Despite themselves",
        "despite themselves",
        "Dimly lit",
        "dimly lit",
        "Don't stop, don't ever stop",
        "don't stop, don't ever stop",
        "down my spine",
        "Dusky nipples",
        "dusky nipples",
        "dust motes danced",
        "embark on this",
        "entwine",
        "ethereal beauty",
        "evident in her eyes",
        "evident in his eyes",
        "evident in their eyes",
        "exhausted and spent",
        "Eyes alight with mirth",
        "Eyes glinted",
        "eyes half-lidded",
        "eyes searching",
        "eyes sparkling mischievously",
        "Eyes sparkling with mischief",
        "eyes sparkling with mischief",
        "Eyes twinkling with mischief",
        "face flushing scarlet",
        "feels a shiver of unease run down her spine",
        "felt a chill run",
        "Felt a mix of X and Y",
        "felt a mix of",
        "felt a twinge",
        "fiddles with the hem of",
        "fidget nervously with the hem of",
        "fidget with the hem of",
        "fidgeting nervously with the hem of",
        "fidgeting with the hem of",
        "Fiery red hair",
        "fiery red hair",
        "filled with an unspoken",
        "finds solace in",
        "flushed crimson",
        "for now, that",
        "for the sake of keeping things",
        "for what comes next",
        "for what felt like",
        "for what seemed like",
        "game changer",
        "gleam",
        "gleaming mischievously",
        "gleaming with curiosity and mischief",
        "gleaming",
        "glint",
        "glinting",
        "glisten",
        "God's above",
        "Gosh",
        "gosh",
        "grasps your chin and forces you to meet",
        "grinning mischievously",
        "grinning",
        "Grins wickedly",
        "grins wickedly",
        "grips like a vice",
        "Half-lidded eyes",
        "half-lidded eyes",
        "half-lidded",
        "haze of pleasure",
        "heart, body and soul belong to you",
        "heart, body and soul",
        "Heart, body, and soul belong to you",
        "heart, body, and soul belong to you",
        "heaving with desire",
        "help but feel a sense",
        "her bare mound",
        "her bare mounds",
        "her body language ",
        "Her cheeks flaming",
        "her cheeks flaming",
        "her eye alight",
        "her eye full",
        "her eye gleam",
        "her eye glint",
        "her eye glow",
        "her eye shin",
        "her eye sparkl",
        "her eye twinkl",
        "her eyes alight",
        "her eyes full",
        "her eyes gleam",
        "her eyes glint",
        "her eyes glow",
        "her eyes shin",
        "her eyes sparkl",
        "her eyes twinkl",
        "her heart aching",
        "her sex",
        "her slick slit",
        "her stiff peaks",
        "her voice barely above a whisper",
        "her voice",
        "Her wet heat",
        "her wet heat",
        "hint of",
        "hips buck",
        "hips swaying",
        "his body language ",
        "his eye alight",
        "his eye full",
        "his eye gleam",
        "his eye glint",
        "his eye glow",
        "his eye shin",
        "his eye sparkl",
        "his eye twinkl",
        "his eyes alight",
        "his eyes full",
        "his eyes gleam",
        "his eyes glint",
        "his eyes glow",
        "his eyes shin",
        "his eyes sparkl",
        "his eyes twinkl",
        "His wet heat",
        "his wet heat",
        "however, it is important to note",
        "however, it is important",
        "however, it's important",
        "hugs every curve",
        "hum with delight",
        "Humble abode",
        "humble abode",
        "huskily",
        "Husky voice",
        "husky voice",
        "Husky whispers",
        "husky whispers",
        "husky",
        "I bite down hard on my lower lip",
        "I bite down on my lower lip",
        "I bite my lip",
        "I bite my lower lip",
        "I don't bite... unless you want me to",
        "i don't bite... unless you want me to",
        "I don't bite...",
        "I don't bite",
        "I shiver at the thought",
        "I want this. I need this.",
        "I want to know. I want to understand.",
        "I want to understand.",
        "important to remember that",
        "in a rhythm",
        "Inner walls clenching around ",
        "inner walls clenching around nothing",
        "Inner walls clenching",
        "inner walls clenching",
        "Iridescent",
        "iridescent",
        "jolt of electricity",
        "journey of mutual understanding",
        "kaleidoscope",
        "Kiss-bruised lips",
        "kiss-bruised lips",
        "knowing smile",
        "knuckle",
        "knuckles turning white",
        "knuckles whitening",
        "knuckles",
        "lay ahead",
        "Lean in",
        "Leans in close",
        "Leans in",
        "Leaves little to the imagination",
        "leaves little to the imagination",
        "life would never be the same again",
        "life would never be the same",
        "Like a predator stalking its prey",
        "like a predator stalking its prey",
        "like an electric shock",
        "little did he kn",
        "Little did he know",
        "little did she kn",
        "Little did she know",
        "little did they kn",
        "Little did they know",
        "little mouse",
        "Long lashes",
        "long lashes",
        "long shadows across",
        "Looking like the cat that got the cream",
        "looking like the cat that got the cream",
        "Lord give me strength",
        "Make me yours, claim me",
        "make me yours, claim me",
        "mask of",
        "maybe... just maybe",
        "maybe that was enough",
        "maybe you'll find you",
        "Maybe, just maybe",
        "maybe, just maybe",
        "maybe, that was enough",
        "Maybe… just maybe",
        "Maybe… maybe",
        "Maybe…just maybe",
        "Maybe…maybe",
        "member",
        "members",
        "Mind, body, and soul",
        "mind, body, and soul",
        "Ministration",
        "ministration",
        "Ministrations",
        "ministrations",
        "minx",
        "mischie",
        "mischievous grin",
        "mischievous",
        "mix of",
        "mixture of",
        "moth to a flame",
        "murmur",
        "murmurs",
        "nails digging",
        "Nails rake angry red lines",
        "nails rake angry red lines",
        "nails raking angry",
        "Naughty boy",
        "nestled deep within",
        "night is still young",
        "No change",
        "No changes.",
        "Oh boy",
        "oh boy",
        "Oh my...",
        "Oh my god",
        "only just getting started",
        "Orchestra",
        "overwhelmed by the sheer",
        "paint",
        "painting",
        "Palpable",
        "palpable",
        "pebbled",
        "penetrated to the hilt",
        "perhaps, just perhaps",
        "Playfully smirking",
        "playfully smirking",
        "Pleasure and pain",
        "pleasure and pain",
        "pooled around her",
        "practiced ease",
        "propriety be damned",
        "Puckered hole",
        "puckered hole",
        "punctuate",
        "punctuating",
        "Pupils blown wide with pleasure",
        "pupils blown wide with pleasure",
        "purr",
        "purring",
        "purrs",
        "Pushing aside a strand of hair",
        "pushing aside a strand of hair",
        "Racing with anticipation",
        "racing with anticipation",
        "ran a nail",
        "ready to face whatever",
        "reckless abandon",
        "reveling in the satisfaction",
        "revulsion warred with reluctance",
        "revulsion warred with reluctant",
        "Rich tapestry",
        "rich tapestry",
        "rivulets of milk",
        "Rivulets of",
        "rivulets of",
        "runs a nail",
        "Same as before",
        "same as before",
        "Same as previous",
        "same as previous",
        "saunters",
        "scarlet",
        "Seductive purrs",
        "seductive purrs",
        "seeing stars",
        "send shockwaves of",
        "sending a shive",
        "sending shive",
        "sending shockwaves of",
        "sends a chill down",
        "sends a shive",
        "sends shive",
        "sensitive flesh",
        "sent a shive",
        "sent shive",
        "sent shockwaves",
        "she bats her eyelids",
        "she bats",
        "she whimpers, biting her lip",
        "she worries her bottom lip",
        "shiver down your spine",
        "shiver down",
        "shiver goes",
        "shiver run",
        "shiver running down my spine",
        "shiver runs down her spine",
        "shiver runs",
        "shiver up",
        "shiver went",
        "shiver",
        "shivers ",
        "shivers down my spine",
        "shivers down the spine",
        "Shivers down",
        "shivers down",
        "shivers run",
        "shivers running up",
        "shivers up her spine",
        "Shivers up",
        "shivers up",
        "shivers",
        "shudder down her spine",
        "shudder down his spine",
        "single tear slips",
        "siren call",
        "Siren call/siren's call",
        "siren's call",
        "Slick folds",
        "slick folds",
        "slick heat",
        "smirk playing on her lips",
        "Softly but firmly",
        "softly but firmly",
        "something else she can't quite put her finger on",
        "soothing balm",
        "spark",
        "sparking",
        "sparks up her spine",
        "Stars burst behind her eyes",
        "stars burst behind her eyes",
        "stars burst",
        "stars",
        "steeling h",
        "steeling herself",
        "steeling himself",
        "steels h",
        "Still lodged deep inside her",
        "Still lodged deep inside him",
        "Still lodged deep inside them",
        "straddles your",
        "stud",
        "sultry tone",
        "sun dipped below the horizon",
        "swallowed hard",
        "swallowing hard",
        "swallows hard",
        "sway hypnotically",
        "swaying",
        "sways hypnotically",
        "symphony of",
        "take your pleasure",
        "takes a deep breath",
        "takes deep breath",
        "tantalizing promise",
        "tapestry of",
        "tear prick",
        "tears prick",
        "tears sting",
        "tears threaten to spill",
        "tears threaten",
        "tentative",
        "testament to",
        "testament",
        "that was enough",
        "The air is thick",
        "the air is thick",
        "the air thick",
        "the atmosphere was charg",
        "The atmosphere",
        "The ball is in your court",
        "the ball is in your court",
        "the din of the crowd",
        "The game is on",
        "the game is on",
        "the hem",
        "The night is still young",
        "the night is still young",
        "the pressure in her loins",
        "the pressure in his loins",
        "the room falls silent",
        "the scene shifts",
        "the shift in",
        "the task at hand",
        "the weight of",
        "the world narrow",
        "The world narrows",
        "their body language ",
        "their eye alight",
        "their eye full",
        "their eye gleam",
        "their eye glint",
        "their eye glow",
        "their eye shin",
        "their eye sparkl",
        "their eye twinkl",
        "their eyes alight",
        "their eyes full",
        "their eyes gleam",
        "their eyes glint",
        "their eyes glow",
        "their eyes shin",
        "their eyes sparkl",
        "their eyes twinkl",
        "Their wet heat",
        "their wet heat",
        "they would face it together",
        "threatens to consume",
        "To meet her gaze",
        "To meet his gaze",
        "toes curl",
        "Tongue darts out",
        "tongue darts out",
        "took a deep breath",
        "Torn between propriety and desire",
        "torn between",
        "Towers over",
        "towers over",
        "Tracing a finger along your jawline",
        "tracing a finger",
        "tracing a nail",
        "transgression",
        "transgressions",
        "tree trunk",
        "trembling hand",
        "twinkle",
        "Unbeknownst to them",
        "unbeknownst to them",
        "unchanged",
        "Unless you want me to.",
        "up my spine",
        "voice a low purr",
        "voice a soft purr",
        "voice barely above a whisper",
        "voice barely audible",
        "voice dripping",
        "voice drops",
        "voice low",
        "voice steady despite",
        "Waggles her eyebrows",
        "waggles her eyebrows",
        "wanton desires",
        "wanton",
        "warring with",
        "was only just beginning",
        "was soft and gentle",
        "was taken aback",
        "wave of pleasure",
        "Waves of arousal pooling in her belly",
        "waves of arousal",
        "waves of pleasure",
        "weapon",
        "wet flesh",
        "wet heat",
        "wet pop",
        "what do you say",
        "what felt like an eternity",
        "what seemed like an eternity",
        "whether you like it or not",
        "whimpers, biting her lip",
        "whimpers, biting his lip",
        "whimpers, biting their lip",
        "whisper",
        "whispering words of passion",
        "whispering",
        "whispers",
        "wild abandon",
        "with a mix",
        "with each breath",
        "with each slow, deliberate movement",
        "with emotion",
        "with genuine emotion",
        "with reckless abandon",
        "with tension",
        "without waiting for a response",
        "words turn into a purr",
        "wretch",
        "wretched",
        "You really know how to treat a lady",
        "you really know how to treat a lady",
        "you're a bold one",
        "yours to take"
    ]
}